#: import Window kivy.core.window.Window

<MainWindow>:
    id: main_win
    canvas.before:
        Color:
            rgba:(1,1,1,1)
        Rectangle:
            pos:self.pos
            size:self.size

    ScreenManager:
        id: scrn_mngr_main
        Screen:
            id :scrn_si
            name:"scrn_si"
        Screen:
            id: scrn_admin
            name:"scrn_admin"
        Screen:
            id:scrn_op
            name:"scrn_op"